name: build

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Setup Traefik
        run: docker network create traefik
      - name: Setup Docker container
        run: |
          cp src/.env-example src/.env
          ./setup.sh
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer
        run: cd src && composer self-update
      - name: Install Dependencies
        run: |
          cd src
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install
      - name: Lint
        run: cd src && composer lint
  # TODO: Lint CSS
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: ['docker', 'lint']
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Harvey
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json-extended'
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "pipeline": "deploy", "prod_compose": true, "healthcheck": ["crazy-color-clash-site-crazy-color-clash-1", "crazy-color-clash-site-crazy-color-clash-2"] }'
